language: php
php:
  - "5.4"
  - "5.5"
  - "5.6"
  - "7.0"
  - "hhvm"

services:
  - redis-server

addons:
  hosts:
    - apiaxle.api.local

before_script:
  - composer install
  - sudo add-apt-repository -y ppa:chris-lea/node.js
  - sudo apt-get update
  - npm install -g apiaxle-proxy apiaxle-api
  - apiaxle-proxy -p 3000 &
  - sleep 3
  - apiaxle-api -p 8000 &
  - sleep 3
  - ./travis.setup.sh
  - cat /etc/hosts

script: 
  - mkdir -p build/logs
  - php vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml tests/
  
after_script:
  - php vendor/bin/coveralls -v
